name: Build when merged into Develop

on:
  push:
    branches:
      - 'develop'
      - 'release/*'

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop